// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/21/2026, 7:01:29 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Administrator/Downloads/nutrimatch_hover_v3/nutrimatch_v3/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Downloads/nutrimatch_hover_v3/nutrimatch_v3/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Downloads/nutrimatch_hover_v3/nutrimatch_v3/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Downloads/nutrimatch_hover_v3/nutrimatch_v3/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Downloads/nutrimatch_hover_v3/nutrimatch_v3/plugins/**/*.{js,ts,mjs}","C:/Users/Administrator/Downloads/nutrimatch_hover_v3/nutrimatch_v3/composables/**/*.{js,ts,mjs}","C:/Users/Administrator/Downloads/nutrimatch_hover_v3/nutrimatch_v3/utils/**/*.{js,ts,mjs}","C:/Users/Administrator/Downloads/nutrimatch_hover_v3/nutrimatch_v3/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Downloads/nutrimatch_hover_v3/nutrimatch_v3/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Downloads/nutrimatch_hover_v3/nutrimatch_v3/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Downloads/nutrimatch_hover_v3/nutrimatch_v3/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;